# Generated by Django 4.2.4 on 2023-09-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('state', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('is_available', models.BooleanField()),
                ('views', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('file', models.ImageField(upload_to='images/')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
